# -*- coding: utf-8 -*-
"""Movie Recommendation.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bvVn_vh-aRMuqO1xCb0jpTucKvfphxQC

## Movie Recommendation
"""

import pandas as pd                                          # Data Manipulation
from sklearn.feature_extraction.text import TfidfVectorizer  # Convert a collection of raw documents to a matrix of TF-IDF features
from sklearn.metrics.pairwise import cosine_similarity       # Compute cosine similarity between samples in X and Y.
import joblib                                                # To save the pipeline
import os
from sklearn.metrics.pairwise import linear_kernel

# Importing Data set

actor_movies = pd.read_csv('/content/Untitled Folder/actor_movies.csv')
actors = pd.read_csv('/content/Untitled Folder/actors.csv')
movie_genres = pd.read_csv('/content/Untitled Folder/movie_genres.csv')
movie_languages = pd.read_csv('/content/Untitled Folder/movie_languages.csv')
movies = pd.read_csv('/content/Untitled Folder/movies.csv')

actor_movies.head(4)

actors.head(4)

movie_genres.head(4)

movie_languages.head(4)

movies.head(4)

# Let's Merge All columns

merge_1 = movies.merge(movie_languages, on = ['movie_id'], how = 'left')
merge_1.head(4)

group_by = merge_1.groupby(['movie_id','movie_name','cinema','classification','release_date','duration_minutes'])['language'].apply(', '.join).reset_index()
group_by.head(4)

merge_2 = group_by.merge(movie_genres, on = ['movie_id'], how = 'left')
merge_2.head(4)

merge_3 = actor_movies.merge(actors, on = ['actor_id'], how = 'left')
merge_3.head(4)

merge_4 = merge_2.merge(merge_3, on = ['movie_id'], how = 'left')
merge_4.head(4)

merge_4 = merge_4.drop(['movie_id','actor_id'], axis = 1)
merge_4.head(4)

Movie_data = merge_4
Movie_data

"""## Data Cleaning"""

missing_columns = Movie_data.columns[Movie_data.isnull().any()]

if len(missing_columns) > 0:
    # If there are missing values, print the columns with missing values
    print("Columns with missing values:")
    print()
    for col in missing_columns:
        missing_count = Movie_data[col].isnull().sum()
        total_count = len(Movie_data)
        missing_percentage = (missing_count / total_count) * 100
        print(f"Column: {col}")
        print(f"Number of missing values: {missing_count}")
        print(f"Percentage of missing values: {missing_percentage:.2f}%")
        print("____________________________")

else:
    # If there are no missing values, print "No missing values"
    print("No missing values")

# Replace missing values with '-'
Movie_data.fillna('-', inplace=True)

missing_columns = Movie_data.columns[Movie_data.isnull().any()]

if len(missing_columns) > 0:
    # If there are missing values, print the columns with missing values
    print("Columns with missing values:")
    print()
    for col in missing_columns:
        missing_count = Movie_data[col].isnull().sum()
        total_count = len(Movie_data)
        missing_percentage = (missing_count / total_count) * 100
        print(f"Column: {col}")
        print(f"Number of missing values: {missing_count}")
        print(f"Percentage of missing values: {missing_percentage:.2f}%")
        print("____________________________")

else:
    # If there are no missing values, print "No missing values"
    print("No missing values")

# Find is there any duplicate values
Movie_data.duplicated().sum()

Movie_data = Movie_data.drop_duplicates()

# Find is there any duplicate values
Movie_data.duplicated().sum()

# Initialize the TF-IDF vectorizer for text features
tfidf_vectorizer = TfidfVectorizer(stop_words='english')

# Create a TF-IDF matrix for text-based features
tfidf_matrix = tfidf_vectorizer.fit_transform(Movie_data['genre'] + ' ' + Movie_data['language'])

# Compute the cosine similarity between movies based on TF-IDF matrix
cosine_sim = linear_kernel(tfidf_matrix, tfidf_matrix)

